=== The plugin configuration

After downloading the plugin , you must activate it.

=== Equipment Configuration 

La configuration des équipements Eco 2 Watt est accessible à partir du menu Plugins puis energie : 

You will find here all the configuration of your equipment: 

* *Name of the equipment*: name of your Eco 2 Watt equipment.
* *Parent object*: Specifies the parent object that owns the equipment,
* *Activate*: to make your equipment active,
* *Visible*: makes your equipment visible on the dashboard.

Then you have two other parameters to configure:

* *Type de source de données* : EJP ou EcoWatt,
* *Région* : afin de préciser les informations de la région que vous souhaitez récupérer.
+
En fonction du choix fait sur le type de source de données, le choix des régions n'est pas le même, puisque chacun d'eux s'applique sur des régions différentes.

** Les régions pour EcoWatt sont : Bretagne ou Provence-Alpes-Côtes d'Azur,
* The EJP regions are: North Zone, South Zone, West Zone, Provence-Alpes-Côtes d'Azur area.


En-dessous vous retrouvez la liste des commandes : 

* *Nom* : le nom de la commande affichée sur le dashboard,
* *Paramètres* : type de commande,
* *Roues crantées* : pour les paramètres avancés de la commande,
* * Test *: allows you to test the command,.
* * Remove * (sign-): allows to delete the order.

Les boutons "Afficher" et "Historiser" sont les boutons habituels d'affichage (ou non) de la commande sur le widget et de son historisation (ou non).

=== Commandes EcoWatt

Pour EcoWatt, 2 commandes existent :

* Aujourd'hui : permet de savoir la tendance pour le jour même quant à la tension sur le réseau électrique,
* Demain : permet de savoir la tendance pour le lendemain quant à la tension sur le réseau électrique.
+
_Pour ces deux commandes les valeurs peuvent être :_

** Verte : la tendance est verte ("tout va bien"),
** Orange : la tendance est orange (il faut faire attention à ses consommations),
** Rouge : la tendance est rouge (il faut réduire ses consommations afin d'éviter une coupure généralisée).

=== Commandes EJP

Pour EJP, 4 commandes existent :

* Today : Is this day on EJP or not,
* Demain : permet de savoir si le lendemain est en EJP ou pas.
+
_Pour ces deux commandes les valeurs peuvent être :_

** Pas d'EJP : la date du jour n'est pas en EJP
** EJP : day is on EJP
** Non déterminé : le site n'a pas communiqué l'information

* Jours EJP restants : indique le nombre de jours EJP restants pour la période EJP (1er novembre - 31 mars) en cours,
* Total de jours EJP : indique le nombre total de jours EJP prévus pour la période EJP (1er novembre - 31 mars) en cours.
+
_Pour ces deux commandes les valeurs sont des nombres._

=== Commandes Tempo

Pour Tempo, 8 commandes existent :

* Aujourd'hui : permet de connaître la couleur du jour,
* Demain : permet de connaître la couleur du lendemain.
+
_Pour ces deux commandes les valeurs peuvent être :_

** BLEU : le jour est "bleu",
** BLANC : le jour est "blanc",
** ROUGE : le jour est "rouge".

Pour chaque couleur de jour (Bleu - Blanc - Rouge) :

* Jours restants : indique le nombre de jours de cette couleur restants pour la période Tempo en cours,
* Total de jours EJP : indique le nombre total de jours de cette couleur prévus pour la période Tempo en cours.
+
_Pour ces commandes les valeurs sont des nombres._

=== Widgets

Les couleurs changent en fonction de la tendance (pour un équipement EcoWatt) et en fonction de l'état EJP (pour un équipement EJP).